Insert into USER_DATA (ID,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD) values (1,'admin@test.com','admin','test','admin');
Insert into USER_DATA (ID,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD) values (2,'doctor@testl.com','doctor','test','doctor');

Insert into MENU_MASTER (MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,MENU_INDEX,MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE) values (1,null,null,1,0,1,'Manage',null,null,null,null);
Insert into MENU_MASTER (MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,MENU_INDEX,MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE) values (2,null,null,1,0,2,'menu1',null,null,null,null);
Insert into MENU_MASTER (MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,MENU_INDEX,MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE) values (3,null,null,1,0,3,'menu2',null,null,null,null);
Insert into MENU_MASTER (MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,MENU_INDEX,MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE) values (4,null,null,1,1,4,'menu3',null,null,null,null);


Insert into SUB_MENU_MASTER (SUB_MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,SUB_MENU_INDEX,SUB_MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE,PARENT_SUB_MENU_ID,MENU_ID) values (1,null,null,1,1,1,'User Roles',null,null,null,'manageRoles',null,1);
Insert into SUB_MENU_MASTER (SUB_MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,SUB_MENU_INDEX,SUB_MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE,PARENT_SUB_MENU_ID,MENU_ID) values (2,null,null,1,1,1,'menu1submenu1',null,null,null,'#',null,2);
Insert into SUB_MENU_MASTER (SUB_MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,SUB_MENU_INDEX,SUB_MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE,PARENT_SUB_MENU_ID,MENU_ID) values (3,null,null,1,1,2,'menu1submenu2',null,null,null,'#',null,2);
Insert into SUB_MENU_MASTER (SUB_MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,SUB_MENU_INDEX,SUB_MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE,PARENT_SUB_MENU_ID,MENU_ID) values (5,null,null,1,1,1,'menu2subsubmen1',null,null,null,'#',null,3);
Insert into SUB_MENU_MASTER (SUB_MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,SUB_MENU_INDEX,SUB_MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE,PARENT_SUB_MENU_ID,MENU_ID) values (6,null,null,1,1,2,'menu2submenu2',null,null,null,'#',null,3);

Insert into ROLE_MASTER (ROLE_ID,INSERT_DATE,INSERT_ID,ACTIVE,MENU_ID,MENU_INDEX,MODIFY_BY,MODIFY_DATE,MODIFY_ID,OPTIONS,SUB_MENU_ID,SUB_MENU_INDEX,USER_ROLE) values (1,null,null,1,1,1,null,null,null,'add,view,delete',1,1,'admin');


