Insert into USER_DATA (ID,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD) values (1,'admin@test.com','admin','test','admin');
Insert into USER_DATA (ID,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD) values (2,'doctor@testl.com','doctor','test','doctor');

Insert into MENU_MASTER (MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,MENU_INDEX,MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE) values (2,null,null,1,null,null,'menu2',null,null,null,null);
Insert into MENU_MASTER (MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,MENU_INDEX,MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE) values (1,null,null,1,null,null,'menu1',null,null,null,null);

Insert into SUB_MENU_MASTER (SUB_MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,SUB_MENU_INDEX,SUB_MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE,PARENT_SUB_MENU_ID,MENU_ID) values (2,null,null,1,null,null,'submenu',null,null,null,null,null,1);
Insert into SUB_MENU_MASTER (SUB_MENU_ID,INSERT_DATE,INSERT_ID,ACTIVE,IS_PAGE_REDIRECT,SUB_MENU_INDEX,SUB_MENU_NAME,MODIFY_BY,MODIFY_DATE,MODIFY_ID,REDIRECT_PAGE,PARENT_SUB_MENU_ID,MENU_ID) values (3,null,null,1,null,null,'submenu1',null,null,null,null,null,1);

